Update l.yml

diff --git a/.github/workflows/l.yml b/.github/workflows/l.yml
--- a/.github/workflows/l.yml
+++ b/.github/workflows/l.yml
@@ -33,18 +33,17 @@ jobs:
     - name: Verify kernel and module files
       run: |
         echo "Checking Image.gz-dtb"
-        ls -l ./out/arch/arm64/boot/Image.gz-dtb || echo "File not found: Image.gz-dtb"
+        if [ ! -f "./out/arch/arm64/boot/Image.gz-dtb" ]; then
+          echo "File not found: Image.gz-dtb"
+          exit 1
+        fi
         echo "Checking memkernel.ko"
-        ls -l ./out/drivers/memkernel/memkernel.ko || echo "File not found: memkernel.ko"
+        if [ ! -f "./out/drivers/memkernel/memkernel.ko" ]; then
+          echo "File not found: memkernel.ko"
+          exit 1
+        fi
 
-    # Шаг 5. Загрузка артефактов (если они были загружены ранее)
-    - name: Download existing artifacts
-      uses: actions/download-artifact@v3
-      with:
-        name: Kernel-Package
-        path: ./downloaded_artifacts
-
-    # Шаг 6. Создание ZIP-архива
+    # Шаг 5. Создание ZIP-архива
     - name: Create ZIP archive
       run: |
         mkdir -p release
@@ -53,10 +52,9 @@ jobs:
         cd release
         zip -r kernel_package.zip *
 
-    # Шаг 7. Загрузка нового ZIP-архива как артефакта
+    # Шаг 6. Загрузка нового ZIP-архива как артефакта
     - name: Upload Kernel ZIP
       uses: actions/upload-artifact@v4
       with:
         name: Kernel-Package
         path: release/kernel_package.zip
-        
